import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "./navbar/page";
import Footer from '@/components/footer';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Covore',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {/* <main className='mx-auto px-4 sm:px-6 md:px-8  xl:px-0 max-w-6xl'> */}
          {children}

        <Footer />
        {/* </main> */}
      </body>
    </html>
  )
}
